"""add remaining models and audits

Revision ID: 1148d84fd87d
Revises: 651250c6aae7
Create Date: 2020-04-19 20:46:33.829262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1148d84fd87d'
down_revision = '651250c6aae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('a_datetime', sa.DateTime(), nullable=True),
    sa.Column('a_user_id', sa.Integer(), nullable=True),
    sa.Column('a_username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('before', sa.String(), nullable=True),
    sa.Column('after', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['keyval.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('key_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('a_datetime', sa.DateTime(), nullable=True),
    sa.Column('a_user_id', sa.Integer(), nullable=True),
    sa.Column('a_username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('before', sa.String(), nullable=True),
    sa.Column('after', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['key.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyval_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('a_datetime', sa.DateTime(), nullable=True),
    sa.Column('a_user_id', sa.Integer(), nullable=True),
    sa.Column('a_username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('before', sa.String(), nullable=True),
    sa.Column('after', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['keyval.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyval_audit')
    op.drop_table('key_audit')
    op.drop_table('instance_audit')
    # ### end Alembic commands ###
