"""added models

Revision ID: 651250c6aae7
Revises: 77c2a991ec22
Create Date: 2020-04-19 15:02:32.358730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651250c6aae7'
down_revision = '77c2a991ec22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bag_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('a_datetime', sa.DateTime(), nullable=True),
    sa.Column('a_user_id', sa.Integer(), nullable=True),
    sa.Column('a_username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('before', sa.String(), nullable=True),
    sa.Column('after', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['bag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bag_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bag_id'], ['bag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('val', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['keyval.id'], ),
    sa.ForeignKeyConstraint(['key_id'], ['key.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('env')
    op.drop_table('parent_audit')
    op.drop_table('parent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('sex', sa.INTEGER(), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('income_amount', sa.NUMERIC(), nullable=True),
    sa.CheckConstraint('is_active IN (0, 1)'),
    sa.CheckConstraint('is_active IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_audit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('a_datetime', sa.DATETIME(), nullable=True),
    sa.Column('a_user_id', sa.INTEGER(), nullable=True),
    sa.Column('a_username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('action', sa.VARCHAR(length=64), nullable=True),
    sa.Column('before', sa.VARCHAR(), nullable=True),
    sa.Column('after', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('env',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('desc', sa.VARCHAR(length=128), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('is_active IN (0, 1)'),
    sa.CheckConstraint('is_active IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('keyval')
    op.drop_table('keyval')
    op.drop_table('bag_audit')
    # ### end Alembic commands ###
